import { Router } from "express";
import { CatalogKind, Prisma, StockMovementType } from "@prisma/client";
import { z } from "zod";
import { prisma } from "../lib/prisma.js";

export const suiteRouter = Router();
const number = (value: Prisma.Decimal | null | undefined) => value == null ? null : Number(value);
const catalogInput = z.object({ kind: z.nativeEnum(CatalogKind), name: z.string().trim().min(1).max(160), sku: z.string().trim().max(80).optional().nullable(), category: z.string().trim().min(1).max(80), costPrice: z.coerce.number().nonnegative().default(0), sellingPrice: z.coerce.number().positive(), quantity: z.coerce.number().nonnegative().default(0), reorderLevel: z.coerce.number().nonnegative().default(0), barcode: z.string().trim().max(120).optional().nullable(), imageUrl: z.string().trim().max(2000).optional().nullable(), durationMinutes: z.coerce.number().int().positive().optional().nullable(), assignedStaff: z.string().trim().max(120).optional().nullable() });

suiteRouter.get("/catalog", async (_req, res, next) => { try { const rows = await prisma.catalogItem.findMany({ orderBy: [{ kind: "asc" }, { name: "asc" }], include: { _count: { select: { saleItems: true } } } }); res.json({ data: rows.map((row) => ({ ...row, costPrice: number(row.costPrice), sellingPrice: number(row.sellingPrice), quantity: number(row.quantity), reorderLevel: number(row.reorderLevel) })) }); } catch (error) { next(error); } });
suiteRouter.post("/catalog", async (req, res, next) => { try { res.status(201).json({ data: await prisma.catalogItem.create({ data: catalogInput.parse(req.body) }) }); } catch (error) { next(error); } });
suiteRouter.patch("/catalog/:id", async (req, res, next) => { try { res.json({ data: await prisma.catalogItem.update({ where: { id: req.params.id }, data: catalogInput.partial().parse(req.body) }) }); } catch (error) { next(error); } });
suiteRouter.delete("/catalog/:id", async (req, res, next) => { try { await prisma.catalogItem.delete({ where: { id: req.params.id } }); res.status(204).send(); } catch (error) { next(error); } });

suiteRouter.get("/inventory", async (_req, res, next) => { try { const [items, movements] = await Promise.all([prisma.catalogItem.findMany({ where: { kind: CatalogKind.PRODUCT }, orderBy: { name: "asc" } }), prisma.inventoryMovement.findMany({ orderBy: { createdAt: "desc" }, take: 100, include: { catalogItem: { select: { name: true, sku: true } } } })]); res.json({ data: { items: items.map((row) => ({ ...row, costPrice: number(row.costPrice), sellingPrice: number(row.sellingPrice), quantity: number(row.quantity), reorderLevel: number(row.reorderLevel) })), movements: movements.map((row) => ({ ...row, quantity: number(row.quantity), beforeQty: number(row.beforeQty), afterQty: number(row.afterQty) })) } }); } catch (error) { next(error); } });
suiteRouter.post("/inventory/movements", async (req, res, next) => { try { const input = z.object({ catalogItemId: z.string(), type: z.nativeEnum(StockMovementType), quantity: z.coerce.number(), reference: z.string().optional().nullable(), notes: z.string().optional().nullable() }).parse(req.body); const result = await prisma.$transaction(async (tx) => { const item = await tx.catalogItem.findUniqueOrThrow({ where: { id: input.catalogItemId } }); const before = Number(item.quantity); const after = input.type === "ADJUSTMENT" ? input.quantity : input.type === "STOCK_OUT" ? before - Math.abs(input.quantity) : before + Math.abs(input.quantity); if (after < 0) throw new Error("Insufficient stock"); await tx.catalogItem.update({ where: { id: item.id }, data: { quantity: after } }); return tx.inventoryMovement.create({ data: { ...input, quantity: Math.abs(input.quantity), beforeQty: before, afterQty: after } }); }); res.status(201).json({ data: result }); } catch (error) { next(error); } });

suiteRouter.get("/customers", async (_req, res, next) => { try { const rows = await prisma.customer.findMany({ orderBy: { name: "asc" }, include: { sales: { orderBy: { soldAt: "desc" }, include: { items: true } } } }); res.json({ data: rows.map((row) => { const totalSpent = row.sales.reduce((sum, sale) => sum + Number(sale.amount), 0); const productCounts = new Map<string, number>(); row.sales.flatMap((sale) => sale.items).forEach((item) => productCounts.set(item.name, (productCounts.get(item.name) ?? 0) + 1)); return { ...row, totalSpent, lastPurchase: row.sales[0]?.soldAt ?? null, orders: row.sales.length, favoriteProduct: [...productCounts].sort((a, b) => b[1] - a[1])[0]?.[0] ?? null, averageOrderValue: row.sales.length ? totalSpent / row.sales.length : 0 }; }) }); } catch (error) { next(error); } });
suiteRouter.get("/suppliers", async (_req, res, next) => { try { const rows = await prisma.supplier.findMany({ orderBy: { name: "asc" }, include: { products: { include: { catalogItem: true } }, purchases: { orderBy: { orderedAt: "desc" } } } }); res.json({ data: rows.map((row) => ({ ...row, outstandingBalance: number(row.outstandingBalance), purchases: row.purchases.map((purchase) => ({ ...purchase, total: number(purchase.total), amountPaid: number(purchase.amountPaid) })) })) }); } catch (error) { next(error); } });
const supplierInput = z.object({ name:z.string().trim().min(1).max(160),contactName:z.string().trim().max(120).optional().nullable(),phone:z.string().trim().max(40).optional().nullable(),email:z.string().trim().email().optional().nullable().or(z.literal("")),address:z.string().trim().max(240).optional().nullable(),paymentTerms:z.string().trim().max(120).optional().nullable(),outstandingBalance:z.coerce.number().nonnegative().optional() });
suiteRouter.post("/suppliers", async (req,res,next)=>{try{res.status(201).json({data:await prisma.supplier.create({data:supplierInput.parse(req.body)})})}catch(error){next(error)}});
suiteRouter.patch("/suppliers/:id", async (req,res,next)=>{try{res.json({data:await prisma.supplier.update({where:{id:req.params.id},data:supplierInput.partial().parse(req.body)})})}catch(error){next(error)}});
suiteRouter.delete("/suppliers/:id", async (req,res,next)=>{try{await prisma.supplier.delete({where:{id:req.params.id}});res.status(204).send()}catch(error){next(error)}});
suiteRouter.get("/purchases", async (_req, res, next) => { try { const rows = await prisma.purchase.findMany({ orderBy: { orderedAt: "desc" }, include: { supplier: true, items: { include: { catalogItem: true } } } }); res.json({ data: rows.map((row) => ({ ...row, total: number(row.total), amountPaid: number(row.amountPaid), items: row.items.map((item) => ({ ...item, quantity: number(item.quantity), receivedQty: number(item.receivedQty), unitCost: number(item.unitCost) })) })) }); } catch (error) { next(error); } });
suiteRouter.post("/purchases", async (req, res, next) => { try { const input = z.object({ supplierId:z.string(),catalogItemId:z.string(),quantity:z.coerce.number().positive(),unitCost:z.coerce.number().positive(),status:z.enum(["DRAFT","ORDERED","RECEIVED"]),amountPaid:z.coerce.number().nonnegative().default(0),dueAt:z.coerce.date().optional().nullable(),notes:z.string().optional().nullable() }).parse(req.body); const reference=`PO-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`; const result=await prisma.$transaction(async tx=>{const total=input.quantity*input.unitCost;const purchase=await tx.purchase.create({data:{reference,supplierId:input.supplierId,status:input.status,total,amountPaid:input.amountPaid,dueAt:input.dueAt,receivedAt:input.status==="RECEIVED"?new Date():null,notes:input.notes,items:{create:{catalogItemId:input.catalogItemId,quantity:input.quantity,unitCost:input.unitCost,receivedQty:input.status==="RECEIVED"?input.quantity:0}}}});if(input.status==="RECEIVED"){const item=await tx.catalogItem.findUniqueOrThrow({where:{id:input.catalogItemId}});const beforeQty=Number(item.quantity);const afterQty=beforeQty+input.quantity;await tx.catalogItem.update({where:{id:item.id},data:{quantity:afterQty}});await tx.inventoryMovement.create({data:{catalogItemId:item.id,type:"STOCK_IN",quantity:input.quantity,beforeQty,afterQty,reference,notes:"Received from purchase order"}})}return purchase});res.status(201).json({data:result}); } catch(error){next(error)} });
suiteRouter.get("/invoices", async (_req, res, next) => { try { const rows = await prisma.invoice.findMany({ orderBy: { issuedAt: "desc" }, include: { items: true } }); res.json({ data: rows.map((row) => ({ ...row, subtotal: number(row.subtotal), taxAmount: number(row.taxAmount), total: number(row.total), amountPaid: number(row.amountPaid), items: row.items.map((item) => ({ ...item, quantity: number(item.quantity), rate: number(item.rate), total: number(item.total) })) })) }); } catch (error) { next(error); } });
suiteRouter.post("/invoices", async (req,res,next)=>{try{const input=z.object({customerName:z.string().trim().min(1),description:z.string().trim().min(1),quantity:z.coerce.number().positive(),rate:z.coerce.number().positive(),dueAt:z.coerce.date(),taxRate:z.coerce.number().min(0).max(100).default(0),notes:z.string().optional().nullable()}).parse(req.body);const subtotal=input.quantity*input.rate;const taxAmount=subtotal*input.taxRate/100;const total=subtotal+taxAmount;const invoice=await prisma.invoice.create({data:{reference:`INV-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`,customerName:input.customerName,status:"UNPAID",subtotal,taxAmount,total,amountPaid:0,dueAt:input.dueAt,notes:input.notes,items:{create:{description:input.description,quantity:input.quantity,rate:input.rate,total:subtotal}}}});res.status(201).json({data:invoice})}catch(error){next(error)}});

suiteRouter.patch("/purchases/:id", async (req,res,next)=>{try{const input=z.object({status:z.enum(["DRAFT","ORDERED","RECEIVED"]).optional(),amountPaid:z.coerce.number().nonnegative().optional(),dueAt:z.coerce.date().optional().nullable(),notes:z.string().optional().nullable()}).parse(req.body);const result=await prisma.$transaction(async tx=>{const current=await tx.purchase.findUniqueOrThrow({where:{id:req.params.id},include:{items:true}});if(input.status==="RECEIVED"&&current.status!=="RECEIVED"){for(const line of current.items){const item=await tx.catalogItem.findUniqueOrThrow({where:{id:line.catalogItemId}});const beforeQty=Number(item.quantity);const received=Number(line.quantity)-Number(line.receivedQty);const afterQty=beforeQty+received;await tx.catalogItem.update({where:{id:item.id},data:{quantity:afterQty}});await tx.purchaseItem.update({where:{id:line.id},data:{receivedQty:line.quantity}});await tx.inventoryMovement.create({data:{catalogItemId:item.id,type:"STOCK_IN",quantity:received,beforeQty,afterQty,reference:current.reference,notes:"Purchase order received"}})}}return tx.purchase.update({where:{id:current.id},data:{...input,receivedAt:input.status==="RECEIVED"?new Date():current.receivedAt}})});res.json({data:result})}catch(error){next(error)}});
suiteRouter.delete("/purchases/:id", async (req,res,next)=>{try{const row=await prisma.purchase.findUniqueOrThrow({where:{id:req.params.id}});if(row.status==="RECEIVED")return res.status(409).json({error:"Received purchase orders cannot be deleted"});await prisma.purchase.delete({where:{id:req.params.id}});res.status(204).send()}catch(error){next(error)}});

suiteRouter.patch("/invoices/:id", async (req,res,next)=>{try{const input=z.object({customerName:z.string().trim().min(1).optional(),status:z.enum(["PAID","PARTIALLY_PAID","UNPAID"]).optional(),amountPaid:z.coerce.number().nonnegative().optional(),dueAt:z.coerce.date().optional(),notes:z.string().optional().nullable()}).parse(req.body);const current=await prisma.invoice.findUniqueOrThrow({where:{id:req.params.id}});const amountPaid=input.status==="PAID"?current.total:input.status==="UNPAID"?0:input.amountPaid;res.json({data:await prisma.invoice.update({where:{id:req.params.id},data:{...input,...(amountPaid!==undefined?{amountPaid}:{})}})})}catch(error){next(error)}});
suiteRouter.delete("/invoices/:id", async (req,res,next)=>{try{await prisma.invoice.delete({where:{id:req.params.id}});res.status(204).send()}catch(error){next(error)}});
